# try...catch文

予想していない異常によりエラーが発生するような場面で意図的に回避するための処理

```
try {
 
    //例外エラーが発生するかもしれない処理
 
} catch( e ) {
 
    //例外エラーが起きた時に実行する処理
 
}
```

# throwで強制的にエラー

# エラーの種類

|エラーの種類|説明|
|:-|:|
|Error|一般的なエラー全般で利用|
|ReferenceError|宣言されていない変数によるエラー|
|SyntaxError|プログラムの文法エラー|
|TypeError|想定された値と異なるデータ型によるエラー|
|RangeError|想定された許容範囲を超えた値によるエラー|
|URIError|不正なURIが指定されたことによるエラー|
|EvalError|不正なeval関数が実行されたエラー|
